name: mimsim CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - releases/*

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                py: [ "3.11" ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                # cf. https://github.com/conda-incubator/setup-miniconda#important
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2
            - uses: conda-incubator/setup-miniconda@v2
              with:
                  python-version: ${{ matrix.pyver }}
                  channels: conda-forge,defaults
                  channel-priority: strict
                  show-channel-urls: true
                  miniforge-version: latest

            - name: Install rubin_sim_data
              run: |
                curl https://www.cosmo.bnl.gov/www/esheldon/data/rubin/rubin_sim_data_mini.tar.gz | tar xvz

            - name: Install imsim and deps
              run: |
                conda config --set always_yes yes
                git clone https://github.com/LSSTDESC/imSim.git imSim-local
                cd imSim-local
                conda install --file etc/standalone_conda_requirements.txt || true
                pip install -e .
                cd ..

            - name: Install skyCatalogs from source
              run: |
                git clone https://github.com/LSSTDESC/skyCatalogs.git skyCatalogs-local
                cd skyCatalogs-local
                git checkout v1.6.0rc2
                pip install --no-build-isolation --no-deps -e .
                cd ..

            - name: Install psfws from source
              run: |
                git clone https://github.com/LSSTDESC/psf-weather-station.git psfws-local
                cd psfws-local
                pip install -e .
                cd ..

            - name: Install mimsim
              run:
                pip install .

            - name: Install test deps
              run:
                conda install pytest pytest-cov flake8 || true

            - name: lint
              run: |
                flake8 mimsim

            - name: Run tests
              run: |
                export IMSIM_HOME=$(realpath ..)
                export RUBIN_SIM_DATA_DIR=$(pwd)/rubin_sim_data_mini
                export SIMS_SED_LIBRARY_DIR=$RUBIN_SIM_DATA_DIR/sims_sed_library

                pytest -vv --cov=mimsim --cov-report=term-missing tests/
